
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_github_actions_development

  
test:
  <<: *default
  database: rails_github_actions_test

production:
  <<: *default
  database: rails_github_actions_production
  username: rails_github_actions
  password: <%= ENV['RAILS_GITHUB_ACTIONS_DATABASE_PASSWORD'] %>
